// src/components/NowPlaying.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { ClientNowPlaying } from "../routes/api/spotify/types";

  let promise: Promise<ClientNowPlaying>;

  onMount(() => {
    promise = fetch("/api/spotify").then(
      (res) => res.json() as Promise<ClientNowPlaying>
    );
  });
</script>

<div class="flex gap-2 items-center text-neutral-300">
  <i class="fa-brands fa-spotify text-lg" />
  {#if promise}
    {#await promise}
      loading...
    {:then res}
      {#if res.isPlaying}
        <a href={res.url} class="interactable"
          >currently listening to {res.title} by {res.artist}</a
        >
      {:else}
        nothing playing right now
      {/if}
    {/await}
  {:else}
    loading...
  {/if}
</div>

// components/NowPlaying.tsx
import { FC } from "react";
import useSWR from "swr";
import { FaSpotify } from "react-icons/fa";
import { ClientNowPlaying } from "types/spotify";

export const NowPlaying: FC<{}> = () => {
  const { data } = useSWR<ClientNowPlaying>("/api/spotify");
  if (!data) return <p className="text-gray-500">Loading...</p>;
  return (
    <div className="flex gap-2 items-center">
      <FaSpotify className="text-[#1DB954] text-lg" />
      {data.isPlaying ? (
        <p className="text-gray-500">
          Playing{" "}
          <a
            href={data.url}
            className="transition text-gray-400 hover:text-gray-300"
          >
            {data.artist} - {data.title}
          </a>
        </p>
      ) : (
        <p className="text-gray-500">Nothing Playing</p>
      )}
    </div>
  );
};
