// pages/404.tsx
import { BackButton } from "components/BackButton";
import { Layout } from "components/Layout";
import { NextPage } from "next";

const FourOhFour: NextPage = () => {
  return (
    <Layout
      title="404"
      description="This page doesn't exist!"
      className="justify-center items-center"
    >
      <div className="flex flex-col gap-3">
        <h1 className="font-heading font-bold text-3xl">Error 404</h1>
        <p className="text-xl">
          The page you were looking for doesn&apos;t exist!
        </p>
        <BackButton href="/" label="Head back to safety" />
      </div>
    </Layout>
  );
};

export default FourOhFour;

// src/routes/404/+page.svelte
<svelte:head>
  <title>iamkneel | 404</title>
</svelte:head>

<div class="space-y-4">
  <h1 class="text-2xl font-bold">Error 404</h1>
  <p>
    Looks like the page you were looking for doesn't exist! <a
      href="/"
      class="underline decoration-zinc-600 underline-offset-4 hover:decoration-zinc-200">Go home</a
    >
  </p>
</div>
